import type { Metadata } from "next";
import Quicksand from 'next/font/local'
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const myFont = Quicksand({
      src: '../../public/fonts/Quicksand-Regular.ttf',
      display: 'swap',
    }

)


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
